// Automatically generated by generate-mapping.js. Do not edit.
window.__featuresMapping = {
  "accessible-error-announcement": [
    "user-pseudos"
  ],
  "respect-os-text-scale": [
    "meta-text-scale"
  ],
  "language-detection": [
    "languagedetector"
  ],
  "language-model": [
    "languagemodel"
  ],
  "summarizer": [
    "summarizer"
  ],
  "translator": [
    "translator"
  ],
  "animate-to-intrinsic-sizes": [
    "calc-size",
    "interpolate-size"
  ],
  "calculate-with-intrinsic-sizes": [
    "calc-size",
    "interpolate-size"
  ],
  "child-state-based-styling": [
    "has",
    "not"
  ],
  "content-based-styling": [
    "has",
    "not"
  ],
  "design-token-reactivity": [
    "container-style-queries"
  ],
  "dynamic-sibling-styling": [
    "sibling-count",
    "trig-functions"
  ],
  "fluid-scaling": [
    "container-queries"
  ],
  "individual-transform-properties": [
    "individual-transforms"
  ],
  "overflow-clipping-control": [
    "overflow-clip",
    "overflow-clip-margin"
  ],
  "reduce-style-repetition": [
    "function"
  ],
  "size-aware-styling": [
    "container-queries"
  ],
  "style-parent-with-has": [
    "user-pseudos"
  ],
  "usage-aware-component-variations": [
    "container-style-queries"
  ],
  "animated-select-picker": [
    "customizable-select"
  ],
  "autofill-address-form": [
    "autofill"
  ],
  "autofill-highlight-inputs": [
    "autofill"
  ],
  "autofill-payment-form": [
    "enterkeyhint",
    "input-email-tel-url",
    "inputmode"
  ],
  "autofill-sign-in-form": [
    "input-email-tel-url",
    "inputmode"
  ],
  "autofill-sign-up-form": [
    "input-email-tel-url",
    "inputmode"
  ],
  "brand-consistent-forms": [
    "accent-color"
  ],
  "branded-select-styling": [
    "customizable-select"
  ],
  "button-group": [
    "customizable-select"
  ],
  "combobox": [
    "customizable-select",
    "datalist"
  ],
  "custom-select-picker-layouts": [
    "customizable-select"
  ],
  "cycle-toggle": [
    "customizable-select"
  ],
  "filterable-select": [
    "customizable-select",
    "view-transitions",
    "transition-behavior",
    "starting-style"
  ],
  "form-fields-automatically-fit-contents": [
    "field-sizing"
  ],
  "rating": [
    "meter",
    "input-range",
    "customizable-select"
  ],
  "required-field-feedback": [
    "user-pseudos"
  ],
  "rich-media-picker": [
    "customizable-select"
  ],
  "select-menu-interaction": [
    "user-pseudos"
  ],
  "slider": [
    "accent-color",
    "input-range"
  ],
  "slider-range": [
    "accent-color",
    "input-range",
    "grid"
  ],
  "slider-tooltip": [
    "anchor-positioning",
    "progress"
  ],
  "switch": [
    "switch-control",
    "accent-color"
  ],
  "tree-view": [
    "details",
    "details-content",
    "customizable-select"
  ],
  "validate-input-after-interaction": [
    "user-pseudos"
  ],
  "migrate-web-app-origin": [
    "app-migration"
  ],
  "accessible-web-components": [
    "aria-attribute-reflection",
    "shadow-dom"
  ],
  "custom-elements": [
    "autonomous-custom-elements"
  ],
  "form-associated-custom-elements": [
    "form-associated-custom-elements"
  ],
  "prerendering-custom-elements": [
    "declarative-shadow-dom"
  ],
  "shadow-dom": [
    "shadow-dom",
    "slot"
  ],
  "styling-web-components": [
    "shadow-parts",
    "host-context",
    "cascade-layers",
    "container-queries"
  ],
  "web-components": [
    "autonomous-custom-elements",
    "shadow-dom",
    "declarative-shadow-dom"
  ],
  "calculate-event-differentials": [
    "temporal"
  ],
  "capture-location-agnostic-data": [
    "temporal"
  ],
  "coordinate-global-events": [
    "temporal"
  ],
  "format-human-readable-durations": [
    "temporal",
    "intl-duration-format"
  ],
  "manage-recurring-intervals": [
    "temporal"
  ],
  "model-partial-time-concepts": [
    "temporal"
  ],
  "stabilize-reactive-state": [
    "temporal"
  ],
  "support-global-calendar-systems": [
    "temporal"
  ],
  "avoid-redundant-large-asset-downloads": [
    "tmp-cross-origin-storage"
  ],
  "batch-analytics-events": [
    "fetchlater",
    "aborting"
  ],
  "break-up-long-tasks": [
    "scheduler"
  ],
  "calculate-total-foreground-time": [
    "page-visibility-state"
  ],
  "conditional-async-dependencies": [
    "top-level-await"
  ],
  "defer-rendering-heavy-content": [
    "content-visibility"
  ],
  "defer-work-until-scroll-ends": [
    "scrollend"
  ],
  "deliver-optimized-decorative-images": [
    "image-set"
  ],
  "serve-alternative-image-formats": [
    "image-set"
  ],
  "deprioritize-background-fetches": [
    "fetch-priority",
    "fetch"
  ],
  "detect-initial-visibility-state": [
    "page-visibility-state",
    "page-visibility"
  ],
  "efficient-background-processing": [
    "content-visibility"
  ],
  "faster-spa-view-transitions": [
    "content-visibility"
  ],
  "flicker-free-client-side-ab-testing": [
    "blocking-render"
  ],
  "full-session-analytics": [
    "fetchlater",
    "aborting"
  ],
  "identify-heavy-scripts": [
    "long-animation-frames"
  ],
  "identify-inp-causes": [
    "long-animation-frames",
    "event-timing"
  ],
  "improve-next-page-load-performance": [
    "speculation-rules"
  ],
  "interactions-in-complex-layouts": [
    "content-visibility"
  ],
  "load-shared-resources-declaratively": [
    "tmp-cross-origin-storage"
  ],
  "optimize-image-priority": [
    "fetch-priority",
    "loading-lazy"
  ],
  "optimize-preload-priority": [
    "fetch-priority",
    "link-rel-preload"
  ],
  "optimize-script-priority": [
    "fetch-priority"
  ],
  "optimize-scroll-stability": [
    "contain-intrinsic-size"
  ],
  "resolution-optimized-pseudo-elements": [
    "image-set"
  ],
  "schedule-tasks-by-priority": [
    "scheduler"
  ],
  "sequence-distributed-events": [
    "temporal"
  ],
  "share-web-fonts-across-origins": [
    "tmp-cross-origin-storage"
  ],
  "streaming-api": [
    "tmp-streaming-api"
  ],
  "privacy": [
    "permissions-policy",
    "partitioned-cookies",
    "fedcm",
    "ua-client-hints"
  ],
  "passkey-authentication": [
    "webauthn",
    "webauthn-signals"
  ],
  "passkey-conditional-create": [
    "webauthn",
    "webauthn-signals"
  ],
  "passkey-management": [
    "webauthn",
    "webauthn-signals"
  ],
  "passkey-reauthentication": [
    "webauthn"
  ],
  "passkey-registration": [
    "webauthn",
    "webauthn-signals"
  ],
  "passkeys": [
    "webauthn"
  ],
  "sanitize-untrusted-html": [
    "sanitizer"
  ],
  "trusted-types": [
    "trusted-types"
  ],
  "carousel-slide-effects": [
    "scroll-driven-animations",
    "scroll-snap"
  ],
  "component-specific-light-dark-theme": [
    "color-scheme",
    "light-dark"
  ],
  "icons": [
    "masks",
    "image-set",
    "svg",
    "container-style-queries",
    "registered-custom-properties",
    "tmp-linked-parameters"
  ],
  "position-aware-tooltips": [
    "container-anchor-position-queries",
    "popover"
  ],
  "pull-to-reveal": [
    "scroll-initial-target",
    "scroll-snap"
  ],
  "resilient-context-menus-and-nested-dropdowns": [
    "anchor-positioning",
    "popover"
  ],
  "scroll-position-aware-elements": [
    "container-scroll-state-queries"
  ],
  "scroll-progress-indicator": [
    "scroll-driven-animations"
  ],
  "scrollability-affordance-hints": [
    "container-scroll-state-queries"
  ],
  "shrinking-header-on-scroll": [
    "scroll-driven-animations"
  ],
  "state-aware-sticky-headers": [
    "container-scroll-state-queries"
  ],
  "anchor-positioning-tab-underline": [
    "anchor-positioning",
    "prefers-reduced-motion"
  ],
  "animate-element-entry-exit": [
    "starting-style",
    "transition-behavior"
  ],
  "animate-to-from-top-layer": [
    "backdrop",
    "dialog",
    "overlay",
    "popover",
    "starting-style",
    "transition-behavior"
  ],
  "carousel-snap-highlights": [
    "container-scroll-state-queries"
  ],
  "consistent-cross-document-transitions": [
    "blocking-render",
    "link-rel-expect",
    "cross-document-view-transitions"
  ],
  "cross-document-transitions": [
    "view-transitions",
    "cross-document-view-transitions",
    "navigation"
  ],
  "custom-button-actions": [
    "invoker-commands"
  ],
  "declarative-dialog-popover-control": [
    "invoker-commands",
    "popover",
    "dialog"
  ],
  "directional-navigation-transitions": [
    "view-transitions",
    "active-view-transition"
  ],
  "drag": [
    "user-select"
  ],
  "drag-and-drop": [
    "user-select"
  ],
  "dynamic-sibling-animations": [
    "sibling-count"
  ],
  "dynamic-sort": [
    "view-transitions",
    "move-before"
  ],
  "group-element-transitions": [
    "view-transitions",
    "view-transition-class"
  ],
  "highlight-text-ranges": [
    "highlight"
  ],
  "interactive-content-reveal": [
    "masks",
    "registered-custom-properties"
  ],
  "interest-triggered-action-previews": [
    "interest-invokers"
  ],
  "interest-triggered-tooltips": [
    "interest-invokers",
    "popover",
    "popover-hint",
    "anchor-positioning"
  ],
  "light-dismiss-a-dialog": [
    "dialog-closedby"
  ],
  "move-dom-element-without-losing-state": [
    "move-before"
  ],
  "overflow-popup": [
    "container-scroll-state-queries",
    "popover",
    "resize-observer"
  ],
  "parallax-scroll-effects": [
    "scroll-driven-animations"
  ],
  "persistent-top-layer-ui": [
    "move-before"
  ],
  "physics-based-easing": [
    "linear-easing"
  ],
  "platform-controls-dismiss-dialog": [
    "dialog-closedby"
  ],
  "responsive-disclosure": [
    "popover",
    "dialog",
    "details",
    "container-queries"
  ],
  "same-document-transitions": [
    "view-transitions"
  ],
  "scroll-entry-exit-effects": [
    "scroll-driven-animations"
  ],
  "scroll-snap-realtime-feedback": [
    "scroll-snap-events",
    "scroll-snap"
  ],
  "scroll-snap-state-sync": [
    "scroll-snap-events",
    "scroll-snap"
  ],
  "scroll-target-on-load": [
    "scroll-initial-target",
    "scroll-into-view"
  ],
  "scrollytelling": [
    "scroll-driven-animations"
  ],
  "search-hidden-content": [
    "details",
    "details-name",
    "hidden-until-found"
  ],
  "sortable-table": [
    "invoker-commands",
    "view-transitions"
  ],
  "swipe-to-remove": [
    "scroll-snap",
    "scroll-initial-target",
    "overscroll-behavior",
    "scrollbar-width",
    "intersection-observer",
    "mutationobserver",
    "resize-observer",
    "web-animations"
  ],
  "accordion": [
    "hidden-until-found",
    "interpolate-size",
    "transition-behavior",
    "starting-style",
    "details-name",
    "details"
  ],
  "breadcrumbs": [
    "border-shape",
    "corner-shape",
    "popover"
  ],
  "card": [
    "has",
    "container-queries",
    "container-style-queries"
  ],
  "carousel": [
    "scroll-snap",
    "scroll-driven-animations",
    "scroll-buttons"
  ],
  "checkbox": [
    "accent-color",
    "indeterminate"
  ],
  "checkbox-group": [
    "subgrid",
    "indeterminate",
    "customizable-select"
  ],
  "content-table": [
    "sticky-positioning",
    "container-scroll-state-queries"
  ],
  "context-menu": [
    "popover",
    "anchor-positioning",
    "menu"
  ],
  "copy-button": [
    "invoker-commands",
    "async-clipboard"
  ],
  "dark-mode-toggle": [
    "color-scheme",
    "prefers-color-scheme",
    "light-dark",
    "has"
  ],
  "data-grid": [
    "field-sizing"
  ],
  "hovercard": [
    "popover",
    "anchor-positioning",
    "interest-invokers",
    "cross-document-view-transitions"
  ],
  "menu": [
    "container-scroll-state-queries",
    "popover",
    "subgrid",
    "menu",
    "sticky-positioning",
    "anchor-positioning"
  ],
  "navbar": [
    "popover"
  ],
  "navigation-drawer": [
    "inert",
    "intersection-observer",
    "popover",
    "registered-custom-properties",
    "scroll-driven-animations",
    "scroll-initial-target",
    "scroll-snap"
  ],
  "persistent-app-tours": [
    "popover",
    "anchor-positioning"
  ],
  "persistent-toast-notifications": [
    "popover",
    "anchor-positioning",
    "sibling-count",
    "transition-behavior"
  ],
  "progress": [
    "accent-color",
    "progress"
  ],
  "progress-ring": [
    "progress",
    "conic-gradients"
  ],
  "scrollspy": [
    "scroll-marker-targets",
    "scroll-target-group"
  ],
  "skeleton": [
    "masks",
    "text-decoration",
    "gradients",
    "prefers-reduced-motion",
    "registered-custom-properties"
  ],
  "spinner": [
    "prefers-reduced-motion",
    "conic-gradients",
    "progress"
  ],
  "stack-drill-down": [
    "inert",
    "intersection-observer",
    "scroll-driven-animations",
    "scroll-snap",
    "scroll-snap-events"
  ],
  "tabs": [
    "anchor-positioning",
    "hidden-until-found",
    "scroll-snap",
    "popover",
    "scroll-buttons"
  ],
  "adapt-scrollbar-to-contrast-preferences": [
    "scrollbar-color",
    "prefers-contrast"
  ],
  "apply-webgl-shaders": [
    "canvas-html"
  ],
  "color-ramps": [
    "relative-color",
    "function",
    "oklab",
    "color-mix"
  ],
  "complex-shapes": [
    "masks",
    "svg"
  ],
  "contrast-color": [
    "contrast-color"
  ],
  "customize-scrollbar-color-and-thickness": [
    "scrollbar-color",
    "scrollbar-width"
  ],
  "dark-mode": [
    "color-scheme",
    "prefers-color-scheme",
    "light-dark",
    "accent-color"
  ],
  "element-shape": [
    "border-shape",
    "corner-shape",
    "border-radius"
  ],
  "export-html-media-from-canvas": [
    "canvas-html"
  ],
  "expose-canvas-content-to-browser-features": [
    "canvas-html"
  ],
  "improve-text-layout-and-legibility": [
    "text-wrap-balance",
    "text-wrap-pretty"
  ],
  "interactive-content-in-3d-scenes": [
    "canvas-html"
  ],
  "precise-text-alignment": [
    "text-box"
  ],
  "prevent-text-wrapping": [
    "text-wrap"
  ],
  "shaped-cutouts": [
    "masks"
  ],
  "soft-edge-content-fade": [
    "masks"
  ],
  "visually-stable-font-fallbacks": [
    "font-size-adjust"
  ],
  "visually-stable-mixed-fonts": [
    "font-size-adjust"
  ],
  "visually-texture-content": [
    "masks"
  ],
  "agentic-forms": [
    "declarative-webmcp"
  ],
  "agentic-javascript-tools": [
    "document-modelcontext"
  ]
};
