import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

const guidesDir = path.resolve('../guides');
const outputFilePath = path.resolve('./features_mapping.gen.js');

const mapping = {}; // usecase -> [feature_ids]

function scanDir(dir) {
  const items = fs.readdirSync(dir, { withFileTypes: true });
  for (const item of items) {
    if (item.isDirectory()) {
       const subDir = path.join(dir, item.name);
       const guidePath = path.join(subDir, 'guide.md');
       if (fs.existsSync(guidePath)) {
          const text = fs.readFileSync(guidePath, 'utf8');
          const parsed = matter(text);
          if (parsed.data && parsed.data['web-feature-ids']) {
              const features = parsed.data['web-feature-ids'];
              if (Array.isArray(features) && features.length > 0) {
                  mapping[item.name] = features;
              }
          }
       }
       scanDir(subDir); // recurse
    }
  }
}

try {
  if (fs.existsSync(guidesDir)) {
     scanDir(guidesDir);
  }

  const jsContent = `// Automatically generated by generate-mapping.js. Do not edit.\nwindow.__featuresMapping = ${JSON.stringify(mapping, null, 2)};\n`;
  fs.writeFileSync(outputFilePath, jsContent);
  console.log(`Successfully generated mapping at ${outputFilePath}`);
} catch (e) {
  console.error('Error generating mapping:', e);
}
