import { test, expect } from '@playwright/test';

// Common interface for parsed declarations
interface CSSDeclaration {
  property: string;
  value: string;
}

// Common interface for parsed rule blocks
interface CSSRuleBlock {
  selector: string;
  bodyText: string;
}

test.describe("CSS Function Grader", () => {

  // A helper function to gather CSS info in browser context
  const getCssInfoInBrowser = () => {
    // 1. Parser to extract blocks with curly braces (handles nested structures like @function or @media)
    function parseCSS(cssText: string): CSSRuleBlock[] {
      // Strip comments
      cssText = cssText.replace(/\/\*[\s\S]*?\*\//g, '');
      const rules: CSSRuleBlock[] = [];
      let pos = 0;
      while (pos < cssText.length) {
        // Skip whitespace
        while (pos < cssText.length && /\s/.test(cssText[pos])) pos++;
        if (pos >= cssText.length) break;
        
        // Read selector / head
        const start = pos;
        let braceCount = 0;
        while (pos < cssText.length) {
          if (cssText[pos] === '{') {
            braceCount++;
            pos++;
            break;
          }
          pos++;
        }
        const selector = cssText.substring(start, pos - 1).trim();
        
        // Read body, tracking braces
        const bodyStart = pos;
        while (pos < cssText.length && braceCount > 0) {
          if (cssText[pos] === '{') {
            braceCount++;
          } else if (cssText[pos] === '}') {
            braceCount--;
          }
          pos++;
        }
        const bodyText = cssText.substring(bodyStart, pos - 1).trim();
        rules.push({ selector, bodyText });
      }
      return rules;
    }

    // 2. Parser to extract individual property declarations
    function parseDeclarations(bodyText: string): CSSDeclaration[] {
      const decls: string[] = [];
      let pos = 0;
      let start = 0;
      let inParens = 0;
      while (pos < bodyText.length) {
        const char = bodyText[pos];
        if (char === '(') inParens++;
        else if (char === ')') inParens--;
        else if (char === ';' && inParens === 0) {
          decls.push(bodyText.substring(start, pos).trim());
          start = pos + 1;
        }
        pos++;
      }
      if (start < bodyText.length) {
        const last = bodyText.substring(start).trim();
        if (last) decls.push(last);
      }
      return decls
        .map(decl => {
          const colonIdx = decl.indexOf(':');
          if (colonIdx === -1) return null;
          return {
            property: decl.substring(0, colonIdx).trim().toLowerCase(),
            value: decl.substring(colonIdx + 1).trim()
          };
        })
        .filter((item): item is CSSDeclaration => item !== null);
    }

    // Gather raw CSS text from style elements
    let cssText = '';
    const styleElements = document.querySelectorAll('style');
    for (const styleEl of Array.from(styleElements)) {
      cssText += (styleEl.textContent || '') + String.fromCharCode(10);
    }
    
    const rawRules = parseCSS(cssText);
    
    // Find custom function names
    const functions: string[] = [];
    for (const rule of rawRules) {
      const m = rule.selector.match(/^@function\s+(--[a-zA-Z0-9_-]+)/);
      if (m) {
        functions.push(m[1]);
      }
    }

    // Map rules to elements
    interface ElementRuleEntry {
      selector: string;
      elements: Element[];
      decls: CSSDeclaration[];
    }
    const elementDecls: ElementRuleEntry[] = [];
    for (const rule of rawRules) {
      if (rule.selector.startsWith('@')) continue;
      try {
        const elements = Array.from(document.querySelectorAll(rule.selector));
        if (elements.length > 0) {
          elementDecls.push({
            selector: rule.selector,
            elements,
            decls: parseDeclarations(rule.bodyText)
          });
        }
      } catch (e) {
        // Ignored for complex selectors
      }
    }

    return {
      functions,
      rawRules,
      elementDecls,
      parseDeclarations // expose helper for inline calls
    };
  };

  test("The body element must have a background-image that contains a linear-gradient generated by a CSS @function", async ({ page }) => {
    const filePath = `file://${process.env.TARGET_FILE || '/private/tmp/ghh-grader-gen-k79soq/work/guides/user-experience/reduce-style-repetition/demo.html'}`;
    await page.goto(filePath);

    const errorMsg = await page.evaluate((getCssInfoStr) => {
      // Evaluate the helper function from string
      const getCssInfo = new Function(`return (${getCssInfoStr})()`)();
      const bodyEl = document.body;
      if (!bodyEl) return 'Body element not found';

      // 1. Verify computed background-image
      const computedBg = window.getComputedStyle(bodyEl).backgroundImage;
      if (!computedBg || !computedBg.includes('linear-gradient')) {
        return `Body computed background-image is not a gradient: "${computedBg}"`;
      }

      // 2. Parse CSS
      const { functions, elementDecls } = getCssInfo;
      if (functions.length === 0) {
        return 'No CSS @functions defined in the stylesheets.';
      }

      // 3. Verify body uses a custom function for background
      const usesFunction = elementDecls.some((entry: any) => {
        if (!entry.elements.includes(bodyEl)) return false;
        return entry.decls.some((decl: any) => {
          if (decl.property !== 'background' && decl.property !== 'background-image') return false;
          return functions.some((fnName: string) => decl.value.includes(fnName + '('));
        });
      });

      if (!usesFunction) {
        return 'No CSS rule applying to the body element uses a custom @function for background or background-image.';
      }

      return null;
    }, getCssInfoInBrowser.toString());

    expect(errorMsg).toBeNull();
  });

  test("All h2 elements must have a background-image that contains a linear-gradient generated by a CSS @function", async ({ page }) => {
    const filePath = `file://${process.env.TARGET_FILE || '/private/tmp/ghh-grader-gen-k79soq/work/guides/user-experience/reduce-style-repetition/demo.html'}`;
    await page.goto(filePath);

    const errorMsg = await page.evaluate((getCssInfoStr) => {
      const getCssInfo = new Function(`return (${getCssInfoStr})()`)();
      const h2Elements = Array.from(document.querySelectorAll('h2'));
      if (h2Elements.length === 0) {
        return 'No h2 elements found in the document.';
      }

      // 1. Verify computed background-image
      for (let i = 0; i < h2Elements.length; i++) {
        const h2 = h2Elements[i];
        const computedBg = window.getComputedStyle(h2).backgroundImage;
        if (!computedBg || !computedBg.includes('linear-gradient')) {
          return `h2 element at index ${i} does not have a gradient in computed background-image: "${computedBg}"`;
        }
      }

      // 2. Parse CSS
      const { functions, elementDecls } = getCssInfo;
      if (functions.length === 0) {
        return 'No CSS @functions defined in the stylesheets.';
      }

      // 3. Verify h2 uses a custom function for background
      for (let i = 0; i < h2Elements.length; i++) {
        const h2 = h2Elements[i];
        const usesFunction = elementDecls.some((entry: any) => {
          if (!entry.elements.includes(h2)) return false;
          return entry.decls.some((decl: any) => {
            if (decl.property !== 'background' && decl.property !== 'background-image') return false;
            return functions.some((fnName: string) => decl.value.includes(fnName + '('));
          });
        });
        if (!usesFunction) {
          return `h2 element at index ${i} is not styled using a custom @function for background or background-image.`;
        }
      }

      return null;
    }, getCssInfoInBrowser.toString());

    expect(errorMsg).toBeNull();
  });

  test("When the viewport is 400px wide, the main element's grid-template-columns must use a function to resolve to a single column (e.g., 1fr)", async ({ page }) => {
    const filePath = `file://${process.env.TARGET_FILE || '/private/tmp/ghh-grader-gen-k79soq/work/guides/user-experience/reduce-style-repetition/demo.html'}`;
    await page.goto(filePath);

    await page.setViewportSize({ width: 400, height: 600 });

    const errorMsg = await page.evaluate((getCssInfoStr) => {
      const getCssInfo = new Function(`return (${getCssInfoStr})()`)();
      const mainEl = document.querySelector('main .grid') || document.querySelector('.grid') || document.querySelector('main');
      if (!mainEl) return 'main element not found.';

      // 1. Verify computed grid-template-columns has exactly 1 column
      const gridStyle = window.getComputedStyle(mainEl).gridTemplateColumns;
      const tracks = gridStyle.trim().split(/\s+/).filter(Boolean);
      if (tracks.length !== 1) {
        return `At 400px viewport, main grid-template-columns has ${tracks.length} tracks instead of 1: "${gridStyle}"`;
      }

      // 2. Parse CSS
      const { functions, elementDecls } = getCssInfo;
      if (functions.length === 0) {
        return 'No CSS @functions defined in the stylesheets.';
      }

      // 3. Verify main uses a custom @function for grid-template-columns
      const usesFunction = elementDecls.some((entry: any) => {
        if (!entry.elements.includes(mainEl)) return false;
        return entry.decls.some((decl: any) => {
          if (decl.property !== 'grid-template-columns') return false;
          return functions.some((fnName: string) => decl.value.includes(fnName + '('));
        });
      });

      if (!usesFunction) {
        return 'No CSS rule applying to the main element uses a custom @function for grid-template-columns.';
      }

      return null;
    }, getCssInfoInBrowser.toString());

    expect(errorMsg).toBeNull();
  });

  test("When the viewport is 1000px wide, the main element's grid-template-columns must use a function to resolve to two columns of equal width", async ({ page }) => {
    const filePath = `file://${process.env.TARGET_FILE || '/private/tmp/ghh-grader-gen-k79soq/work/guides/user-experience/reduce-style-repetition/demo.html'}`;
    await page.goto(filePath);

    await page.setViewportSize({ width: 1000, height: 600 });

    const errorMsg = await page.evaluate((getCssInfoStr) => {
      const getCssInfo = new Function(`return (${getCssInfoStr})()`)();
      const mainEl = document.querySelector('main .grid') || document.querySelector('.grid') || document.querySelector('main');
      if (!mainEl) return 'main element not found.';

      // 1. Verify computed grid-template-columns has exactly 2 columns of equal width
      const gridStyle = window.getComputedStyle(mainEl).gridTemplateColumns;
      const tracks = gridStyle.trim().split(/\s+/).filter(Boolean);
      if (tracks.length !== 2) {
        return `At 1000px viewport, main grid-template-columns has ${tracks.length} tracks instead of 2: "${gridStyle}"`;
      }

      if (tracks[0] !== tracks[1]) {
        return `At 1000px viewport, main grid columns are not of equal width: "${gridStyle}"`;
      }

      // 2. Parse CSS
      const { functions, elementDecls } = getCssInfo;
      if (functions.length === 0) {
        return 'No CSS @functions defined in the stylesheets.';
      }

      // 3. Verify main uses a custom @function for grid-template-columns
      const usesFunction = elementDecls.some((entry: any) => {
        if (!entry.elements.includes(mainEl)) return false;
        return entry.decls.some((decl: any) => {
          if (decl.property !== 'grid-template-columns') return false;
          return functions.some((fnName: string) => decl.value.includes(fnName + '('));
        });
      });

      if (!usesFunction) {
        return 'No CSS rule applying to the main element uses a custom @function for grid-template-columns.';
      }

      return null;
    }, getCssInfoInBrowser.toString());

    expect(errorMsg).toBeNull();
  });

  test("All uses of functions must be preceded with a fallback value for the same property", async ({ page }) => {
    const filePath = `file://${process.env.TARGET_FILE || '/private/tmp/ghh-grader-gen-k79soq/work/guides/user-experience/reduce-style-repetition/demo.html'}`;
    await page.goto(filePath);

    const errorMsg = await page.evaluate((getCssInfoStr) => {
      const getCssInfo = new Function(`return (${getCssInfoStr})()`)();
      const { functions, rawRules, parseDeclarations } = getCssInfo;

      if (functions.length === 0) {
        return 'No CSS @functions defined in the stylesheets.';
      }

      let totalFunctionUses = 0;

      for (const rule of rawRules) {
        if (rule.selector.startsWith('@')) continue;
        const decls = parseDeclarations(rule.bodyText);
        
        for (let i = 0; i < decls.length; i++) {
          const decl = decls[i];
          const usesFn = functions.some((fnName: string) => decl.value.includes(fnName + '('));
          if (usesFn) {
            totalFunctionUses++;
            // Check if there is a declaration before this one with the same property that does NOT use any function
            let hasFallback = false;
            for (let j = 0; j < i; j++) {
              const prevDecl = decls[j];
              if (prevDecl.property === decl.property) {
                const prevUsesFn = functions.some((fnName: string) => prevDecl.value.includes(fnName + '('));
                if (!prevUsesFn) {
                  hasFallback = true;
                  break;
                }
              }
            }
            if (!hasFallback) {
              return `Function use "${decl.property}: ${decl.value}" is not preceded by a fallback value for "${decl.property}" in rule "${rule.selector}".`;
            }
          }
        }
      }

      if (totalFunctionUses === 0) {
        return 'No CSS @function calls were found in stylesheet declarations.';
      }

      return null;
    }, getCssInfoInBrowser.toString());

    expect(errorMsg).toBeNull();
  });

});
